version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-container-gerard_zad1b
    environment:
      - POSTGRES_DB=gerard_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all" ]